import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { api } from "../utils/api";

import MovieCard from "../components/MovieCard";

const Home: NextPage = () => {
  const { data: movies } = api.movies.getAllMovies.useQuery();

  const [searchTerm, setSearchTerm] = useState("");

  const handleSearchChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setSearchTerm(event.target.value);
  };

  const filteredMovies = movies?.filter((movie) => {
    const title = movie.title.toLowerCase();
    const category = movie.category?.toLowerCase();

    if (title.includes(searchTerm.toLowerCase())) {
      return true;
    }

    if (category && category.includes(searchTerm.toLowerCase())) {
      return true;
    }

    return false;
  });

  const nowShowingMovies = filteredMovies?.filter(
    (movie) => movie.status === "CURRENTLYSHOWING"
  );
  const comingSoonMovies = filteredMovies?.filter(
    (movie) => movie.status === "COMINGSOON"
  );

  return (
    <>
      <Head>
        <title>Cinema EBooking System</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white">
        <div className="mx-58 my-8 grid grid-cols-10 gap-8">
          <div className="col-span-1 flex items-center justify-center text-lg font-bold text-gray-800">
            Search:
          </div>
          <input
            className="col-span-3 rounded-md border border-gray-300 px-4 py-2 shadow-sm focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500 sm:text-sm"
            placeholder="Search Movies"
            value={searchTerm}
            onChange={handleSearchChange}
          />
        </div>

        <div className="mx-64 mt-10 font-bold">Now Showing</div>
        <div className="mx-64 mt-8 grid grid-cols-3 gap-8">
          {nowShowingMovies?.map((movie) => {
            return <MovieCard movie={movie} key={`MovieCard-${movie.id}`} />;
          })}
        </div>
        <div className="mx-64 mt-10 font-bold">Coming Soon</div>
        <div className="mx-64 mt-8 grid grid-cols-3 gap-8">
          {comingSoonMovies?.map((movie) => {
            return <MovieCard movie={movie} key={`MovieCard-${movie.id}`} />;
          })}
        </div>
      </main>
    </>
  );
};

export default Home;
